theme:minima
title: Roos Flash LLC
author: GitHub User
email: roosflash@roosflash.com
description: > # this means to ignore newlines until "baseurl:"
 Developing developer, here. Officer of luxury exploration yachts. Want to transition to a career with greater flexability that offers greater connection with my family, friends and neighbors
# social links
github_username: roosflash your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
